language: generic 
# Hey travis we need sudo permisions for docker.
sudo: required
# Tell travis that we need these services preinstalled.
services:
  - docker

before_install:
  - docker build -t gpamfilis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gpamfilis/docker-react npm run test